### ISSUE TITLE
File remains locked after running flow in QtConsole on Windows

### ISSUE THREAD

**Issue by as2875** [datahq/dataflows#145]
Run the following in QtConsole on Windows (which is what the popular Spyder IDE does).

```python
import dataflows

data = [
    {"data": "Hello"},
    {"data": "World"}
]

f = dataflows.Flow(
    data,
    dataflows.dump_to_zip("package.zip")
)

f.process()
```
The file `package.zip` remains locked after the code finishes running and can only be accessed after closing the console.

(@lwinfree, @sje30)

**Comment by akariv** [comment]
Thanks for reporting @as2875 !
