### ISSUE TITLE
datapackages with invalid date/time formats should be dumped and loaded successfully

### ISSUE THREAD

**Issue by OriHoch** [datahq/dataflows#41]
Seems there is a problem with datapackages created with the non-standard date/time format

The packages are loaded fine but are saved incorrectly and can't be loaded

This affects the checkpoint as it depends on dump_to_path and load - which makes it "misbehave" in some cases

see example here - 
https://gist.github.com/OriHoch/5e5b608f31916f27beafb40376860761

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gist/OriHoch/5e5b608f31916f27beafb40376860761/master?filepath=checkpoint%20from%20old%20datapackage%20with%20non-standard%20date%20time.ipynb)

**Comment by akariv** [comment]
I'm guessing the problem is that `dump_to_path` modifies the date format on save but does not update the datapackage, so a discrepancy is created.
I'll handle this tomorrow.
