### ISSUE TITLE
Join takes too long time (or hangs) to process the data

### ISSUE THREAD

**Issue by zelima** [datahq/dataflows#66]
I'm trying to solve this exercise https://github.com/ViderumGlobal/programming-exercise but join needs so big time to process that I thought it just hang and could not finish the task. Don't see any while loops in [join.py](https://github.com/datahq/dataflows/blob/master/dataflows/processors/join.py) so I doubt I'm getting in an infinite loop, making me think that it's just slow.

I simplified the code
```
from dataflows import Flow, load, join, printer, filter_rows, 

def filter_over_10(rows):
    for row in rows:
        if row.get('order') is not None and row.get('order') > 10:
            continue
        yield row

res = Flow(
        load('data/movies/datapackage.json'),
        load('data/credits/datapackage.json'),
        filter_over_10,
        filter_rows(not_equals=[{'revenue': 0}], resources=['tmdb_5000_movies']),
        filter_rows(not_equals=[{'gender': 0}], resources=['tmdb_5000_credits']),
        join('tmdb_5000_movies', ['id'], 'tmdb_5000_credits', ['id'], fields={'revenue':{}}, full=False),
        printer(),
).results()
```

- movies is ~4000 rows
- credits ~40000 after the filter

**Comment by akariv** [comment]
Are you using the speedup version (the one using leveldb)?

**Comment by akariv** [comment]
See here:
https://github.com/datahq/dataflows/blob/b818aaac1b70abee8abc48fdf1b7933acfee335b/TUTORIAL.md#installation

**Comment by zelima** [comment]
That a **lot** faster

**Comment by akariv** [comment]
:D
