### ISSUE TITLE
Local test runs create many files not present in codebase or gitignore

### ISSUE THREAD

**Issue by roll** [datahq/dataflows#98]
# Overview

After `py.test` we end up with a lot neither checked-in nor ignored files.

**Comment by rufuspollock** [comment]
@roll can you do a PR please 😄

**Comment by roll** [comment]
I think it might be better to fix it on another level (having special folder for test outputs or something) but I don't know how it works internally so, for now, I've just added all this artifacts to `gitignore` - https://github.com/datahq/dataflows/pull/101

cc @akariv
